### PR TITLE
PrismRecordEvent to broadcast when PrismRecord created

### PR DESCRIPTION
**Pull request by whimxiqal**
Created a PrismRecordEvent which is thrown when a PrismRecord is about to be saved. Other plugins have the option to listen for it and cancel the event or read from the PrismRecord.

### CODE REVIEW

**Comment by viveleroi** [comment]
@LXGaming Any thoughts?

Seems fine to me, although would we better be served by a name like `PrismRecordPreSave` or something indicating this occurs prior to a save?

**Comment by whimxiqal** [comment]
I agree! Let me know if there's anything else.

**Comment by LXGaming** [comment]
Yeah this seems alright, However I am curious as to how many events this would create and if that would cause issues with Sponge but in theory it should be fine.

**Comment by whimxiqal** [comment]
> Yeah this seems alright, However I am curious as to how many events this would create and if that would cause issues with Sponge but in theory it should be fine.

I don't think that should be an issue considering how many events Sponge throws around in the event manager.

**Pull request merged**
