### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Column01**
### Updates
- Fixed formatting issues
- Updated build URL (source for url [here](https://forums.spongepowered.org/t/prism-official-thread-v3-0-beta/1137))

### Proposed addons:
- Sponge API version info
- Update images that broke over the years (I.E Lines 7 and 142)

### CODE REVIEW

**Comment by viveleroi** [comment]
Do you want to make the proposed fixes as part of this PR, or a new one?

The only image we should fix is the "header art", the entire paypal section can be dropped.

**Comment by Column01** [comment]
I'd need to know what the original image was for the header art.

You don't take paypal donations anymore? Only reason I started this was cause I wanted to donate when I get paid. Maybe we can update it to a new URL if you need to cause I noticed it was for Botsko LLC or something like that

**Comment by Column01** [comment]
Do you have the original banner art? Otherwise I might be able to whip something up.

**Comment by LXGaming** [comment]
This might be it: https://media.forgecdn.net/avatars/71/994/636163324604152029.jpg
Source: https://dev.bukkit.org/projects/prism

**Comment by viveleroi** [comment]
That's it. I have a local copy as well but it's the same size.

**Comment by Column01** [comment]
Added stuff

**Pull request merged**
